### ISSUE TITLE
File not closed in Python code

### ISSUE THREAD

**Issue by yrahul3910** [yrahul3910/employee-attrition-predictor#3]
Opened file must be closed using `f.close()` in the Python code.

**Comment by rahulnandyala** [comment]
will do it and make other additions give me time

**Comment by yrahul3910** [comment]
Sure. Can we have this Thursday or Friday as a deadline?

**Comment by rahulnandyala** [comment]
DONE!!!!!!

**Comment by yrahul3910** [comment]
Seems perfect 👍
